apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: appauthtest-cronjob
  labels:
    app: appauthtest
spec:
  schedule: "0/1 * * * *"
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 30 # must start in x seconds
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 7200
      activeDeadlineSeconds: 600 # must complete in x seconds
      template:
        metadata:
          labels:
            app: appauthtest
            aadpodidbinding: appauthtest # reference to aapodidentitybinding
        spec:
          containers:
          - name: appauthtest
            image: kwaazaar/appauthtest:latest
          restartPolicy: Never